# Generated by Django 6.0.5 on 2026-06-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(db_index=True, max_length=100)),
                ('row_id', models.BigIntegerField(db_index=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('payload_json', models.JSONField(default=dict)),
                ('file_paths', models.JSONField(blank=True, default=list)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['table_name', 'row_id'], name='sync_manage_table_n_cc0e0b_idx'), models.Index(fields=['status', 'created_at'], name='sync_manage_status_bffb3e_idx'), models.Index(fields=['table_name', 'row_id', 'action'], name='sync_manage_table_n_f78dcf_idx')],
            },
        ),
    ]
