"""
Django settings for ONLportal project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_q',
    'accounts',
    'sync_manager',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ONLportal.urls'



import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Tell Django to look in a global 'templates' folder at your project root
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True, # Tells Django to look inside each app's 'templates' folder
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ONLportal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# OFFLINE-FIRST: SQLite is always the local primary database.
# Supabase PostgreSQL is a remote sync target, never a direct Django connection.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ================================================================
# Supabase Remote Sync Configuration (read by the sync_manager app)
# ================================================================
SUPABASE_URL = config('SUPABASE_URL')
SUPABASE_KEY = config('SUPABASE_KEY')
# Full DATABASE_URL is kept for optional direct psql inspection only.
SUPABASE_DATABASE_URL = config('DATABASE_URL', default='')


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = '/login/'

# Email Configuration (for password reset)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')


# ================================================================
# django-q2 Configuration (Background Task Queue with Django ORM Broker)
# ================================================================
Q_CLUSTER = {
    'name': 'ONLportal',
    'workers': 2,                 # 2 worker processes
    'recycle': 500,               # recycle worker after 500 tasks
    'timeout': 120,               # 120s task timeout
    'retry': 300,                 # retry failed tasks after 300s (must be > timeout)
    'compress': True,             # compress task payloads in the DB
    'save_limit': 250,            # keep last 250 task results
    'queue_limit': 500,           # max queued tasks
    'cpu_affinity': 1,            # pin each worker to a CPU core
    'label': 'Django Q2',
    'broker_class': 'django_q.brokers.orm.ORM',  # Django ORM broker (no Redis)
    'redis': None,                # explicit: no Redis dependency
    'guard_cycle': 5,             # monitor / heartbeat every 5s
    'poll': 2,                    # poll DB for new tasks every 2s
    'catch_up': False,            # don't replay missed cron tasks on start
}

# Sync schedule (django-q2 cron syntax)
Q_SCHEDULE = {
    # Check connectivity every 30 seconds
    'check_connectivity': {
        'func': 'sync_manager.scheduler.check_connectivity',
        'schedule': 30,
        'repeats': -1,
    },
    # Attempt sync every 60 seconds (only runs if online)
    'sync_all_pending': {
        'func': 'sync_manager.scheduler.sync_all_pending',
        'schedule': 60,
        'repeats': -1,
    },
}

# ================================================================
# Offline Sync Settings
# ================================================================
SYNC_CONNECTIVITY_TIMEOUT = 5    # seconds to wait for a connectivity check
SYNC_BATCH_SIZE = 50             # max sync records to process per batch
SYNC_RETRY_MAX = 5               # max retries before marking a record 'failed' permanently
SYNC_CONNECTIVITY_CACHE_TTL = 10 # seconds before re-checking connectivity
